export const detailedAnswersDialogStyles = {
  dialogContent: "max-w-3xl max-h-[90vh] overflow-y-auto",
  backToResponsesButton: "flex items-start gap-4",
  leftArrow: "w-4 h-4",
  llmAndRankBadgeContainer: "flex items-center justify-between pt-2",
  llmAndDateContainer: "flex items-center gap-3",
  dateText: "text-sm text-muted-foreground",
  bodyContainer: "space-y-6 py-4",
  fullResponseText: "text-base font-semibold text-foreground",
  answerText: "text-sm text-foreground leading-relaxed",
  personasContainer: "pt-4 border-t border-border",
  targetedPersonasTitle: "text-sm font-semibold text-foreground mb-3",
  personasBadgesContainer: "flex flex-wrap gap-2",
  queryDetailsContainer: "pt-4 border-t border-border",
  queryDetailsTitle: "text-sm font-semibold text-foreground mb-3",
  cityAndCountryTextContainer: "space-y-2 text-sm",
  labelValuePair: "flex items-center gap-2",
  textMuted: "text-muted-foreground",
  textForeground: "text-foreground",
};
